Formula/adoptopenjdk-openjdk10.rb
Just updated the link and hash of the updated release.
=> Update adoptopenjdk-openjdk10.rb to latest release (10.0.2+13)

Formula/adoptopenjdk-openjdk11.rb, README.md
Add latest binary for adoptopenjdk
=> add adoptopenjdk11

Info.plist
=> add sample plist file

Casks/adoptopenjdk10.rb, README.md
=> add adoptopenjdk10 cask

Casks/adoptopenjdk11-openj9.rb, README.md
=> Adoptopenjdk11 openj9

Casks/adoptopenjdk11.rb
=> Update to latest release

Casks/adoptopenjdk8-jre.rb, README.md
=> WIP: Create adoptopenjdk8-jre.rb

Casks/adoptopenjdk8-openj9.rb, README.md
=> Add adoptopenjdk8-openj9.rb

Casks/adoptopenjdk9.rb, README.md
Fix some problems reported by `brew cask style`.
=> Fix style and typo

Casks/adoptopenjdk8-openj9-jre.rb, README.md
=> Add adoptopenjdk8-openj9-jre.rb

Casks/adoptopenjdk8-openj9.rb
=> switch to using PKG

Casks/adoptopenjdk8-openj9-jre.rb
=> switch j9-jre to use pkg

Casks/adoptopenjdk8-jre.rb
=> switch adoptopenjdk8-jre to use pkg

Casks/adoptopenjdk12-openj9.rb, README.md
=> add jdk12 j9 cask

Casks/adoptopenjd12-openj9-jre
=> add 12 j9-jre

Casks/adoptopenjdk12.rb, README.md
closes: https://github.com/AdoptOpenJDK/homebrew-openjdk/issues/90
=> add adoptopenjdk12.rb

Casks/adoptopenjdk12-jre.rb
=> add adoptopenjdk12-jre.rb

Casks/adoptopenjdk8-jre.rb
=> update adoptopenjdk8-jre to 8u212-b03

Casks/adoptopenjdk11-jre.rb
=> update adoptopenjdk11-jre to 11.0.3+7

Casks/adoptopenjdk11.rb
=> update adoptopenjdk11 to 11.0.3+7

Casks/adoptopenjdk11-openj9.rb
=> update adoptopenjdk11-openj9 to 11.0.3+7

Casks/adoptopenjdk11-openj9-jre.rb
=> update adoptopenjdk11-openj9-jre to 11.0.3+7

Casks/adoptopenjdk11-jre.rb
=> switch 11-jre to use pkg

Casks/adoptopenjdk11-openj9.rb
=> switch 11-openj9 to use pkg

Casks/adoptopenjdk11-openj9-jre.rb
=> switch 11-openj9-jre to pkg

Casks/adoptopenjdk12-jre.rb
=> update openjdk12-hotspot-jre to 12.0.1+12

Casks/adoptopenjdk12.rb
=> update openjdk12-hotspot-jdk to 12.0.1+12

Casks/adoptopenjdk12-openj9-jre.rb
=> update openjdk12-openj9-jre to 12.0.1+12

Casks/adoptopenjdk12-openj9.rb
=> update openjdk12-openj9-jdk to 12.0.1+12

Casks/adoptopenjdk8.rb
=> update adoptopenjdk8 to 8u212b04

Casks/adoptopenjdk8-jre.rb
=> update adoptopenjdk8-jre to 8u212b04

Casks/adoptopenjdk8-openj9.rb
=> update adoptopenjdk8-openj9 to 8u212b04

Casks/adoptopenjdk8-openj9-jre.rb
=> update adoptopenjdk8-openj9-jre to 8u212b04

Casks/adoptopenjdk8-openj9-large.rb
=> update adoptopenjdk8-openj9-large to 8u212b04

Casks/adoptopenjdk8-openj9-jre-large.rb, README.md
=> add 8-j9-jre-xl

Casks/adoptopenjdk11-openj9-jre-large.rb, README.md
=> add 11-j9-jre-xl

Casks/adoptopenjdk12.rb
=> update adoptopenjdk12 to 12.0.2-b10

Casks/adoptopenjdk12-jre.rb
=> update adoptopenjdk12-jre to 12.0.2-b10

Casks/adoptopenjdk12-openj9.rb
=> update adoptopenjdk12-openj9 to 12.0.2-b10

Casks/adoptopenjdk12-openj9-jre.rb
=> update adoptopenjdk12-openj9-jre to 12.0.2-b10

Casks/adoptopenjdk11-jre.rb, Casks/adoptopenjdk11-openj9-jre-large.rb, Casks/adoptopenjdk11-openj9-jre.rb, Casks/adoptopenjdk11-openj9.rb, Casks/adoptopenjdk11.rb, Casks/adoptopenjdk12-jre.rb, Casks/adoptopenjdk12-openj9-jre.rb, Casks/adoptopenjdk12-openj9-large.rb, Casks/adoptopenjdk12-openj9.rb, Casks/adoptopenjdk12.rb, README.md
=> uninstall version fix

Casks/adoptopenjdk12-openj9-jre-large.rb, README.md
=> add adoptopenjdk12-openj9-jre-large.rb

auto_updater.sh
This script allows us to auto update the casks
=> add auto_updater to allow jenkins to update casks

auto_updater.sh
=> add force push if needed to overwrite existing branch

auto_updater.sh
=> change version logic for jdk8

auto_updater.sh
=> fix broken jdk12 update

Casks/adoptopenjdk13-jre.rb, Casks/adoptopenjdk13-openj9-jre-large.rb, Casks/adoptopenjdk13-openj9-jre.rb, Casks/adoptopenjdk13-openj9-large.rb, Casks/adoptopenjdk13-openj9.rb, Casks/adoptopenjdk13.rb, README.md
=> add jdk13 template

Casks/adoptopenjdk13-jre.rb, Casks/adoptopenjdk13-openj9-jre-large.rb, Casks/adoptopenjdk13-openj9-jre.rb, Casks/adoptopenjdk13-openj9-large.rb, Casks/adoptopenjdk13-openj9.rb, Casks/adoptopenjdk13.rb
=> add fake values for 13

auto_updater.sh
=> add --force option

Templates/adoptopenjdk.rb.tmpl, auto_updater.sh
as requested in https://github.com/AdoptOpenJDK/homebrew-openjdk/issues/176#issuecomment-557552883
=> add verbose post installation information for pkg

auto_updater.sh
updates the updater to use the v3 API.
uses python to parse the JSON output (removes the horrible awk/sed etc)
=> migrate auto_updater.sh to use v3 api

README.md
No casks changed, no homebrew tests run.
=> Update README to include openjdk 14

README.md, auto_updater.sh, casks.txt
Makes it easier to add new major versions
=> make it easier to add a new major version

auto_updater.sh
=> fix updater

auto_updater.sh
linked to https://github.com/AdoptOpenJDK/openjdk-build/issues/1696
fixes: https://github.com/AdoptOpenJDK/homebrew-openjdk/issues/355
=> use full semver version for versioning casks

auto_updater.sh
=> make build_number work for jdk8u

README.md, auto_updater.sh, casks.txt
I didn't test every cask.
Fixes #94.
=> Add latest casks for JRE, OpenJ9, OpenJ9 XL

Templates/adoptopenjdk.rb.tmpl, auto_updater.sh
=> fix cask updater

README.md
=> Add jdk15 openj9 to readme

.github/workflows/cache.yml, .github/workflows/updater.yml
=> switch to using actions

Casks/adoptopenjdk-openj9-jre-large.rb, Casks/adoptopenjdk-openj9-large.rb, Casks/adoptopenjdk11-openj9-jre-large.rb, Casks/adoptopenjdk11-openj9-large.rb, Casks/adoptopenjdk15-openj9-jre-large.rb, Casks/adoptopenjdk15-openj9-large.rb, Casks/adoptopenjdk8-openj9-jre-large.rb, Casks/adoptopenjdk8-openj9-large.rb, README.md, casks.txt
Fixes: https://github.com/AdoptOpenJDK/homebrew-openjdk/issues/521
=> deprecated large heap casks
