AdoptOpenJDK/homebrew-openjdk

Casks/adoptopenjdk8.rb
Casks/adoptopenjdk9.rb
README.md

Remove the deprecation notice from the readme.
Add casks that will be removed in https://github.com/Homebrew/homebrew-cask-versions/pull/6453

add adoptopenjdk 8/9 casks

---

Casks/adoptopenjdk8.rb

CA Certs are missing in 8-181-b13 so TLS won't work
See: https://github.com/AdoptOpenJDK/openjdk-build/issues/676

Updated AdoptOpenJDK8 to 8-192-b12

---

Casks/adoptopenjdk8.rb

Update adoptopenjdk8.rb to jdk8u202-b08

---

Casks/adoptopenjdk8.rb

Corrected SHA256 checksum in adoptopenjdk8.rb for jdk8u202-b08

---

Casks/adoptopenjdk11-jre.rb
README.md

To solve issue https://github.com/AdoptOpenJDK/homebrew-openjdk/issues/24, here is a cask for the JRE version of AdoptOpenJDK 11. The install location is:
`/Library/Java/JavaVirtualMachines/adoptopenjdk-11.0.2.jre/Contents/Home`
I've added the following entry to the `Info.plist`:
```
<key>JVMCapabilities</key>
<array>
<string>CommandLine</string>
</array>
```
This allow to find the JRE through `/usr/libexec/java_home -V`.
Please review this cask and I will add the other JREs.

Add adoptopenjdk11-jre.rb

---

Casks/adoptopenjdk11-openj9.rb

closes: https://github.com/AdoptOpenJDK/homebrew-openjdk/issues/75

update 11-j9 to jdk-11.0.2+9_openj9-0.12.1

---

Casks/adoptopenjdk11-openj9-jre.rb
README.md

This should add adoptopenjdk11-open9-jre according to #24.

Adds adoptopenjdk11-open9-jre for #24

---

Casks/adoptopenjdk11-openj9.rb

This should fix #77 for the cask adoptopenjdk11-openj9 11.0.2:9

Open Update adoptopenjdk11-openj9 11.0.2:9

---

Casks/adoptopenjdk11-jre.rb

This should fix #77 for the cask adoptopenjdk11-jre 11.0.2:9

 Open Update adoptopenjdk11-jre 11.0.2:9

---

Casks/adoptopenjdk11.rb

This should fix #77 for the cask adoptopenjdk11 11.0.2:9

Update adoptopenjdk11 11.0.2:9

---

Casks/adoptopenjdk8-openj9-jre.rb

update adoptopenjdk8-openj9-jre to 8u121-b03

---

Casks/adoptopenjdk8.rb

update adoptopenjdk8 to 8u212-b03

---

Casks/adoptopenjdk8-openj9.rb

update adoptopenjdk8-openj9 to8u212-b03

---

Casks/adoptopenjdk8-openj9-large.rb
README.md

Solves https://github.com/AdoptOpenJDK/homebrew-openjdk/issues/87
Install from `OpenJDK8U-jdk_x64_mac_openj9_macosXL_8u212b03_openj9-0.14.0.pkg`

Add adoptopenjdk8-openj9-large.rb

---

Casks/adoptopenjdk10.rb

fixes: https://github.com/AdoptOpenJDK/homebrew-openjdk/issues/126

update jdk10 link

---

Casks/adoptopenjdk11-jre.rb
Casks/adoptopenjdk11-openj9-jre-large.rb
Casks/adoptopenjdk11-openj9-jre.rb
Casks/adoptopenjdk11-openj9-large.rb
Casks/adoptopenjdk11-openj9.rb
Casks/adoptopenjdk11.rb
Casks/adoptopenjdk12-jre.rb
Casks/adoptopenjdk12-openj9-jre.rb
Casks/adoptopenjdk12-openj9.rb
Casks/adoptopenjdk12.rb
Casks/adoptopenjdk8-jre.rb
Casks/adoptopenjdk8-openj9-jre-large.rb
Casks/adoptopenjdk8-openj9-jre.rb
Casks/adoptopenjdk8-openj9-large.rb
Casks/adoptopenjdk8-openj9.rb

The homebrew core community hit the same issue with the appcast URL. This PR switches our appcast URLs to be the same as the upstream ones: https://github.com/Homebrew/homebrew-cask/pull/66457

fix appcast issues

---

Casks/adoptopenjdk12-openj9-large.rb

fix shasum for adoptopenjdk12-openj9-large

---

Casks/adoptopenjdk11-openj9-jre.rb

update adoptopenjdk11-openj9-jre.rb to 11.0.4,11

---

Casks/adoptopenjdk11.rb

update adoptopenjdk11.rb to 11.0.4,11

---

Casks/adoptopenjdk11-openj9.rb

update adoptopenjdk11-openj9.rb to 11.0.4,11

---

Casks/adoptopenjdk11-openj9-large.rb

update adoptopenjdk11-openj9-large.rb to 11.0.4,11

---

Casks/adoptopenjdk11-openj9-jre-large.rb

update adoptopenjdk11-openj9-jre-large.rb to 11.0.4,11

---

Casks/adoptopenjdk11-jre.rb

update adoptopenjdk11-jre.rb to 11.0.4,11

---

README.md

References: 
- https://blog.openj9.org/2018/06/12/openj9-xl-heap/
- https://github.com/AdoptOpenJDK/openjdk-build/issues/341
- https://github.com/eclipse/openj9/issues/643
- https://www.eclipse.org/openj9/docs/xcompressedrefs/

Update README to clarify large heap

---

README.md

https://github.com/AdoptOpenJDK/homebrew-openjdk/issues/111

Add doc to switch between different JDK versions

---

README.md

It is not notarized but installed with quarantine flags. As a result, it does not work out of the box. And because it is maintained by Homebrew-Casks and we cannot agree with them how to package/distribute it, we cannot easily fix it. Our tap does not have that problem.

Explain installation instructions

---

README.md

As a fish shell user, I also need to [switch between JDK version](https://github.com/AdoptOpenJDK/homebrew-openjdk/pull/314). The fish shell function syntax is different than the bash syntax. I hope by adding the fish shell snippet in the readme.md, it would help other fish shell users.
`version` variable in fish shell is a [special variables](https://fishshell.com/docs/current/#special-variables). So, I use `java_version` instead.

Add fish shell support for switching between JDK version on README.md

---

README.md

Updated brew install commands to use `brew install --cask` instead of `brew cask install` to avoid the below warning produced by Homebrew.
`
Warning: Calling brew cask install is deprecated! Use brew install [--cask] instead.
`

Update brew install commands in readme
